# Schema for the configuration files of the User Deleter module.
user_deleter.settings:
  type: config_object
  label: 'User Deleter settings'
  mapping:
    example:
      type: string
      label: 'Example'
